In [1]:
# Loading raw FAERS data files — dollar sign is the separator in these files
import pandas as pd
demo = pd.read_csv(r"C:\Users\Vaishnavi\Desktop\p'covigilance project data\DEMO25Q4.txt", sep="$", low_memory=False)
drug = pd.read_csv(r"C:\Users\Vaishnavi\Desktop\p'covigilance project data\DRUG25Q4.txt", sep="$", low_memory=False)
reac = pd.read_csv(r"C:\Users\Vaishnavi\Desktop\p'covigilance project data\OUTC25Q4.txt", sep="$", low_memory=False)
outc = pd.read_csv(r"C:\Users\Vaishnavi\Desktop\p'covigilance project data\REAC25Q4.txt", sep="$", low_memory=False)

In [2]:
demo.head()

,primaryid,caseid,caseversion,i_f_code,event_dt,mfr_dt,init_fda_dt,fda_dt,rept_cod,auth_num,...,age_grp,sex,e_sub,wt,wt_cod,rept_dt,to_mfr,occp_cod,reporter_country,occr_country
0,100324053,10032405,3,F,NaN,20251110,20140320,20251120,EXP,NaN,...,NaN,F,Y,NaN,NaN,20251120,NaN,NaN,CA,NaN
1,1012809821,10128098,21,F,20140219.0,20251003,20140428,20251010,EXP,NaN,...,A,F,Y,70.00,KG,20251010,NaN,MD,CA,CA
2,101406268,10140626,8,F,20120301.0,20250929,20140429,20251007,EXP,NaN,...,A,F,Y,77.09,KG,20251007,NaN,CN,US,US
3,101515934,10151593,4,F,NaN,20251014,20140505,20251020,EXP,NaN,...,A,F,Y,NaN,NaN,20251020,NaN,HP,EU,EU
4,1016133068,10161330,68,F,NaN,20251002,20140509,20251009,EXP,NaN,...,E,F,Y,63.00,KG,20251009,NaN,CN,CA,CA

In [3]:
drug.head()

,primaryid,caseid,drug_seq,role_cod,drugname,prod_ai,val_vbm,route,dose_vbm,cum_dose_chr,cum_dose_unit,dechal,rechal,lot_num,exp_dt,nda_num,dose_amt,dose_unit,dose_form,dose_freq
0,100324053,10032405,1,PS,CEFPROZIL,CEFPROZIL,1,Unknown,"UNK UNK,Two Times a Day,",NaN,NaN,D,NaN,NaN,NaN,65381.0,NaN,NaN,NaN,QD
1,100324053,10032405,2,SS,PNEUMOCOCCAL VACCINE POLYVALENT NOS,"PNEUMOCOCCAL VACCINE, POLYVALENT",1,Unknown,"UNK, once",NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100324053,10032405,3,SS,PNEUMOCOCCAL 13-VALENT CONJUGATE VACCINE,PNEUMOCOCCAL 13-VALENT CONJUGATE VACCINE,1,Unknown,"1 DF,UNK,",NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100324053,10032405,4,SS,PNEUMOCOCCAL 7-VALENT CONJUGATE VACCINE (DIPHT...,PNEUMOCOCCAL 7-VALENT CONJUGATE VACCINE (DIPHT...,1,Unknown,"1 DF,UNK,",NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100324053,10032405,5,SS,PNEUMOVAX 23,"PNEUMOCOCCAL VACCINE, POLYVALENT 23",1,Unknown,UNK,NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
reac.head()

    primaryid    caseid outc_cod
0   100324053  10032405       DE
1   100324053  10032405       OT
2  1012809821  10128098       OT
3   101406268  10140626       HO
4   101406268  10140626       OT

In [5]:
outc.head()

    primaryid    caseid                                     pt drug_rec_act
0   100324053  10032405                       Drug ineffective          NaN
1   100324053  10032405                        Drug resistance          NaN
2   100324053  10032405                Meningitis pneumococcal          NaN
3  1012809821  10128098                Injection site reaction          NaN
4  1012809821  10128098  General physical health deterioration          NaN

In [6]:
demo.columns

Index(['primaryid', 'caseid', 'caseversion', 'i_f_code', 'event_dt', 'mfr_dt',
       'init_fda_dt', 'fda_dt', 'rept_cod', 'auth_num', 'mfr_num', 'mfr_sndr',
       'lit_ref', 'age', 'age_cod', 'age_grp', 'sex', 'e_sub', 'wt', 'wt_cod',
       'rept_dt', 'to_mfr', 'occp_cod', 'reporter_country', 'occr_country'],
      dtype='object')

In [7]:
drug.columns

Index(['primaryid', 'caseid', 'drug_seq', 'role_cod', 'drugname', 'prod_ai',
       'val_vbm', 'route', 'dose_vbm', 'cum_dose_chr', 'cum_dose_unit',
       'dechal', 'rechal', 'lot_num', 'exp_dt', 'nda_num', 'dose_amt',
       'dose_unit', 'dose_form', 'dose_freq'],
      dtype='object')

In [8]:
reac.columns

Index(['primaryid', 'caseid', 'outc_cod'], dtype='object')

In [9]:
outc.columns

Index(['primaryid', 'caseid', 'pt', 'drug_rec_act'], dtype='object')

In [10]:
import pandas as pd
reac = pd.read_csv(r"C:\Users\Vaishnavi\Desktop\p'covigilance project data\REAC25Q4.txt",sep="$", low_memory=False)
outc = pd.read_csv(r"C:\Users\Vaishnavi\Desktop\p'covigilance project data\OUTC25Q4.txt", sep="$", low_memory=False)

In [11]:
outc['outc_cod'].value_counts()

outc_cod
OT    161458
HO     80556
DE     26291
LT     13126
DS      6065
CA      1371
RI       854
Name: count, dtype: int64

In [12]:
# Creating binary serious variable — 1 if outcome is clinically serious, 0 otherwise
outc['serious']= outc['outc_cod'].isin(['HO','DE','LT','DS','CA','RI']).astype(int)

In [13]:
outc[['outc_cod','serious']].head()

  outc_cod  serious
0       DE        1
1       OT        0
2       OT        0
3       HO        1
4       OT        0

In [14]:
# Keeping only columns needed for analysis
import pandas as pd
demo_small = demo[['primaryid','age','sex']]
drug_small = drug[['primaryid','drugname']].drop_duplicates()
reac_small = reac[['primaryid','pt']]
outc_small = outc[['primaryid','serious']]

In [15]:
# Collapsing outc_small to one row per patient
# max() ensures patient is flagged serious=1 if any outcome was serious
outc_small=outc_small.groupby('primaryid')['serious'].max().reset_index()

In [16]:
print(outc_small.shape)

(218342, 2)

In [17]:
# Extract primaryid column
# Check which values are duplicated
# Count how many duplicates exist
print(outc_small['primaryid'].duplicated().sum())

0

In [18]:
print(outc_small['serious'].value_counts())

serious
0    109473
1    108869
Name: count, dtype: int64

In [19]:
# FAERS data is not a random sample of all adverse events.It is heavily skewed towards serious cases — because serious cases are more likely to be reported.

In [20]:
# Merging all 4 datasets on primaryid using left join
# Left join ensures we keep all patients from demo_small as our base
# Patients missing from other tables are kept with NaN values
# Step 1 — attach drug information to each patient
# drug_small has many rows per patient so df1 will expand in rows
import pandas as pd
df1=pd.merge(demo_small,drug_small, on='primaryid', how='left')
# Step 2 — attach reaction information
# reac_small also has many rows per patient so df2 expands further
df2=pd.merge(df1, reac_small,on='primaryid',how='left')
# Step 3 — attach serious outcome flag
# outc_small has one row per patient so shape stays same
df3=pd.merge(df2, outc_small, on='primaryid', how='left')

In [21]:
# Verifying merge results — shape, sample rows, and missing values
print(df3.shape)
print (df3.head())
print(df3.isnull().sum())

(11062547, 6)
   primaryid  age sex                             drugname  \
0  100324053  7.0   F                            CEFPROZIL
1  100324053  7.0   F                            CEFPROZIL
2  100324053  7.0   F                            CEFPROZIL
3  100324053  7.0   F  PNEUMOCOCCAL VACCINE POLYVALENT NOS
4  100324053  7.0   F  PNEUMOCOCCAL VACCINE POLYVALENT NOS

                        pt  serious
0         Drug ineffective      1.0
1          Drug resistance      1.0
2  Meningitis pneumococcal      1.0
3         Drug ineffective      1.0
4          Drug resistance      1.0
primaryid          0
age          2345675
sex          1536726
drugname           0
pt                 0
serious       959274
dtype: int64

In [22]:
 #dropped rows where serious was NaN because assuming a missing outcome as non-serious would introduce bias into our statistical analysis. dropped rows where serious was NaN because assuming a missing outcome as non-serious would introduce bias into our statistical analysis.

df3=df3.dropna(subset=['serious'])

In [23]:
print(df3.shape)

(10103273, 6)

In [24]:
#The Rule

#Only drop rows where your critical analysis variable is missing.
#Never use dropna() blindly.
#dropna() without subset drops all rows with any null value — this would remove valid drug-reaction records just because demographic data was missing, unnecessarily reducing our sample size and introducing selection bias.

In [25]:
print (df3.head())

   primaryid  age sex                             drugname  \
0  100324053  7.0   F                            CEFPROZIL
1  100324053  7.0   F                            CEFPROZIL
2  100324053  7.0   F                            CEFPROZIL
3  100324053  7.0   F  PNEUMOCOCCAL VACCINE POLYVALENT NOS
4  100324053  7.0   F  PNEUMOCOCCAL VACCINE POLYVALENT NOS

                        pt  serious
0         Drug ineffective      1.0
1          Drug resistance      1.0
2  Meningitis pneumococcal      1.0
3         Drug ineffective      1.0
4          Drug resistance      1.0

In [26]:
#For each patient — you need to:

#Get their list of drugs
#Generate all 2-drug combinations
#Store each combination with their primaryid

In [27]:
from itertools import combinations
# step1:Group drugs by patient
drug_groups= drug_small.groupby('primaryid') ['drugname'].apply(list)

In [28]:
#step2: generate combinations for each patient
combo_list=[]

In [34]:
from itertools import combinations

combo_list = []

for primaryid, drugs in drug_groups.items():
    for combo in combinations(drugs, 2):
        combo_list.append({
            'primaryid': primaryid,
            'drug1': combo[0],
            'drug2': combo[1]
        })

combo_df = pd.DataFrame(combo_list)

In [35]:
print(combo_df.shape)
print(combo_df.head())

(9068516, 3)
   primaryid        drug1         drug2
0   42021115  HALOPERIDOL  ITRACONAZOLE
1   42021115  HALOPERIDOL  LEVOFLOXACIN
2   42021115  HALOPERIDOL      DIAZEPAM
3   42021115  HALOPERIDOL      NYSTATIN
4   42021115  HALOPERIDOL  PANTOPRAZOLE

In [37]:
df3.to_csv(r"C:\Users\Vaishnavi\Desktop\faers_cleaned.csv", index=False)
print("File saved successfully")

File saved successfully

In [39]:
# Take a clean sample of 500,000 rows
df_sample = df3.sample(n=500000, random_state=42)

# Export sample
df_sample.to_csv(r"C:\Users\Vaishnavi\Desktop\faers_cleaned.csv", index=False)

print("Sample saved successfully")
print(df_sample.shape)
print(df_sample['serious'].value_counts())

Sample saved successfully
(500000, 6)
serious
1.0    385645
0.0    114355
Name: count, dtype: int64